image: maven:3.6.0-jdk-8-alpine

variables:
  MAVEN_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -DdependencyLocationsEnabled=false -Dmaven.repo.local=.m2/repository"
  MVN_OPTS: "-s .m2/settings.xml --batch-mode -DskipTests -DskipITs"
  MVN_OPTS_SONAR: "-s .m2/settings.xml --batch-mode -DskipTests -DskipITs "
  MVN_OPTS_BUILD: "-T 4 -s .m2/settings.xml --batch-mode -DskipTests -DskipITs "
  #DOCKER_HOST: $ENV_DOCKER_HOST
  DOCKER_USER: $ENV_DOCKER_USER
  DOCKER_PASSWORD: $ENV_DOCKER_PASSWORD
  GIT_PROJECT_PATH: "git@${GITLAB_URL}:${CI_PROJECT_PATH}.git"
  GIT_PROJECT_PATH_SSH: "ssh://git@${GITLAB_URL}/${CI_PROJECT_PATH}"

stages:
  - quality
  - version-promotion
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - docker login - u $DOCKER_HOST -p $DOCKER_PASSWORD

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .m2/repository/

test:
  stage: quality
  script:
    - mvn $MVN_OPTS test
